// Code generated by "stringer -type=RenderbufferType"; DO NOT EDIT.

package raw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorBuffer-1]
	_ = x[DepthStencilBuffer-2]
}

const _RenderbufferType_name = "ColorBufferDepthStencilBuffer"

var _RenderbufferType_index = [...]uint8{0, 11, 29}

func (i RenderbufferType) String() string {
	i -= 1
	if i < 0 || i >= RenderbufferType(len(_RenderbufferType_index)-1) {
		return "RenderbufferType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RenderbufferType_name[_RenderbufferType_index[i]:_RenderbufferType_index[i+1]]
}
