// Code generated by "stringer -type=ShaderType"; DO NOT EDIT.

package raw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VertexShader-1]
	_ = x[FragmentShader-2]
}

const _ShaderType_name = "VertexShaderFragmentShader"

var _ShaderType_index = [...]uint8{0, 12, 26}

func (i ShaderType) String() string {
	i -= 1
	if i < 0 || i >= ShaderType(len(_ShaderType_index)-1) {
		return "ShaderType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ShaderType_name[_ShaderType_index[i]:_ShaderType_index[i+1]]
}
