// Code generated by "stringer -type=CullFace"; DO NOT EDIT.

package gl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FrontFace-1]
	_ = x[BackFace-2]
}

const _CullFace_name = "FrontFaceBackFace"

var _CullFace_index = [...]uint8{0, 9, 17}

func (i CullFace) String() string {
	i -= 1
	if i < 0 || i >= CullFace(len(_CullFace_index)-1) {
		return "CullFace(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CullFace_name[_CullFace_index[i]:_CullFace_index[i+1]]
}
