// Code generated by "stringer -type=PrimitiveDrawMode"; DO NOT EDIT.

package gl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Points-0]
	_ = x[Lines-1]
	_ = x[Triangles-2]
}

const _PrimitiveDrawMode_name = "PointsLinesTriangles"

var _PrimitiveDrawMode_index = [...]uint8{0, 6, 11, 20}

func (i PrimitiveDrawMode) String() string {
	if i < 0 || i >= PrimitiveDrawMode(len(_PrimitiveDrawMode_index)-1) {
		return "PrimitiveDrawMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveDrawMode_name[_PrimitiveDrawMode_index[i]:_PrimitiveDrawMode_index[i+1]]
}
